export const SUCCEES_REGISTER = 'RESTRADO CON EXITO'
export const FAILED_REGISTER = 'RESTRADO FALLIDO'

export const SUCCEES_LOGIN = 'LOGIN CON EXITO'
export const FAILED_LOGIN = 'LOGIN FALLIDO'

export const SUCCEES_MEDIA = 'MEDIA CON EXITO'
export const FAILED_MEDIA = 'MEDIA FALLIDO'

export const SUCCEES_GET_USER = 'GET USER CON EXITO'
export const FAILED_GET_USER = 'GET USER FALLIDO'

export const SUCCEES_GET_MEDIA_USER = 'GET USER MEDIA EXITO'
export const FAILED_GET_MEDIA_USER = 'GET USER MEDIA FALLIDO'