export const SUCCEES_REGISTER = 'RESTRADO CON EXITO'
export const FAILED_REGISTER = 'RESTRADO FALLIDO'

export const SUCCEES_LOGIN = 'LOGIN CON EXITO'
export const FAILED_LOGIN = 'LOGIN FALLIDO'

export const SUCCEES_MEDIA = 'MEDIA CON EXITO'
export const FAILED_MEDIA = 'MEDIA FALLIDO'

export const SUCCEES_GET_USER = 'GET USER CON EXITO'
export const FAILED_GET_USER = 'GET USER FALLIDO'

export const SUCCEES_GET_MEDIA_USER = 'GET USER MEDIA EXITO'
export const FAILED_GET_MEDIA_USER = 'GET USER MEDIA FALLIDO'

export const SUCCEES_GET_WALLET = 'GET WALLET CON EXITO'
export const FAILED_GET_WALLLET = 'GET WALLET FALLIDO'


export const SUCCEES_CREATE_TRANSACTIONS = 'CREATE TRANSACTIONS CON EXITO'
export const FAILED_CREATE_TRANSACTIONS = 'CREATE TRANSACTIONS FALLIDO'


export const SUCCEES_CREATE_COMMENT = 'CREATE COMMENT CON EXITO'
export const FAILED_CREATE_COMMENT = 'CREATE COMMENT FALLIDO'

export const SUCCEES_CREATE_LIKE = 'CREATE LIKE CON EXITO'
export const FAILED_CREATE_LIKE  = 'CREATE LIKE FALLIDO'


export const SUCCEES_CREATE_VIEW = 'CREATE VIEW CON EXITO'
export const FAILED_CREATE_VIEW = 'CREATE VIEW FALLIDO'


export const SUCCEES_GET_COMMENT = 'GET COMMENT CON EXITO'
export const FAILED_GET_COMMENT = 'GET COMMENT FALLIDO'

export const SUCCEES_CREATE_FOLLOWER = 'CREATE FOLLOWER CON EXITO'
export const FAILED_CREATE_FOLLOWER = 'CREATE FOLLOWER FALLIDO'

export const SUCCEES_CREATE_STORY = 'CREATE STORY CON EXITO';
export const FAILED_CREATE_STORY = 'CREATE STORY FALLIDO';

export const SUCCEES_ACTIVE_STORIES = 'GET ACTIVE STORIES CON EXITO';
export const FAILED_ACTIVE_STORIES = 'GET ACTIVE STORIES FALLIDO';

export const SUCCEES_ACTIVE_GIFTS = 'GET ACTIVE GIFT CON EXITO';
export const FAILED_ACTIVE_GIFTS = 'GET ACTIVE GIFT FALLIDO';

export const SUCCEES_GET_ONE_ACTIVE_GIFTS = 'GET ONE GIFT CON EXITO';
export const FAILED_GET_ONE_ACTIVE_GIFTS = 'GET ONE GIFT FALLIDO';

export const SUCCEES_RECIVED_GIFTS = 'GET RECIVED GIFT CON EXITO';
export const FAILED_RECEVED_GIFTS = 'GET RECIVED GIFT FALLIDO';

export const SUCCEES_RECIVED_GIFTS_BY_USER = 'GET RECIVED GIFT BY USER CON EXITO';
export const FAILED_RECEVED_GIFTS_BY_USER = 'GET RECIVED GIFT BY USER FALLIDO';

export const SUCCEES_USER_STORIES = 'GET USER STORIES CON EXITO';
export const FAILED_USER_STORIES = 'GET USER STORIES FALLIDO';

export const SUCCEES_VIEW_STORY = 'VIEW STORY CON EXITO';
export const FAILED_VIEW_STORY = 'VIEW STORY FALLIDO';

export const SUCCEES_LIKE_STORY = 'LIKE STORY CON EXITO';
export const FAILED_LIKE_STORY = 'LIKE STORY FALLIDO';

export const SUCCEES_SEND_GIFT_STORY = 'LIKE STORY CON EXITO';
export const FAILED_SEND_GIFT_STORY = 'LIKE STORY FALLIDO';

export const SUCCEES_STORY_VIEWERS = 'GET STORY VIEWERS CON EXITO';
export const FAILED_STORY_VIEWERS = 'GET STORY VIEWERS FALLIDO';

export const SUCCEES_DELETE_STORY = 'DELETE STORY CON EXITO';
export const FAILED_DELETE_STORY = 'DELETE STORY FALLIDO';
