export const SUCCEES_REGISTER = 'RESTRADO CON EXITO'
export const FAILED_REGISTER = 'RESTRADO FALLIDO'

export const SUCCEES_LOGIN = 'LOGIN CON EXITO'
export const FAILED_LOGIN = 'LOGIN FALLIDO'

export const SUCCEES_MEDIA = 'MEDIA CON EXITO'
export const FAILED_MEDIA = 'MEDIA FALLIDO'

export const SUCCEES_GET_USER = 'GET USER CON EXITO'
export const FAILED_GET_USER = 'GET USER FALLIDO'
export const USER_NOT_FOUND = 'USER_NOT_FOUND'
export const CLEAR_USER = 'CLEAR_USER'

export const SUCCEES_GET_MEDIA_USER = 'GET USER MEDIA EXITO'
export const FAILED_GET_MEDIA_USER = 'GET USER MEDIA FALLIDO'

export const SUCCEES_GET_WALLET = 'GET WALLET CON EXITO'
export const FAILED_GET_WALLLET = 'GET WALLET FALLIDO'

export const SUCCEES_BUY_TOKENS = 'BUY TOKENS CON EXITO'
export const FAILED_BUY_TOKENS = 'BUY TOKENS FALLIDO'

export const SUCCEES_CREATE_TRANSACTIONS = 'CREATE TRANSACTIONS CON EXITO'
export const FAILED_CREATE_TRANSACTIONS = 'CREATE TRANSACTIONS FALLIDO'

export const SUCCEES_CREATE_DEPOSIT = 'CREATE DEPOSIT CON EXITO'
export const FAILED_CREATE_DEPOSIT = 'CREATE DEPOSIT FALLIDO'

export const SUCCEES_WITHDRAW = 'WITHDRAW CON EXITO'
export const FAILED_WITHDRAW = 'WITHDRAW FALLIDO'
export const SUCCEES_CREATE_COMMENT = 'CREATE COMMENT CON EXITO'
export const FAILED_CREATE_COMMENT = 'CREATE COMMENT FALLIDO'

export const SUCCEES_CREATE_LIKE = 'CREATE LIKE CON EXITO'
export const FAILED_CREATE_LIKE = 'CREATE LIKE FALLIDO'


export const SUCCEES_CREATE_VIEW = 'CREATE VIEW CON EXITO'
export const FAILED_CREATE_VIEW = 'CREATE VIEW FALLIDO'


export const SUCCEES_GET_COMMENT = 'GET COMMENT CON EXITO'
export const FAILED_GET_COMMENT = 'GET COMMENT FALLIDO'

export const SUCCEES_CREATE_FOLLOWER = 'CREATE FOLLOWER CON EXITO'
export const FAILED_CREATE_FOLLOWER = 'CREATE FOLLOWER FALLIDO'

export const SUCCEES_CREATE_STORY = 'CREATE STORY CON EXITO';
export const FAILED_CREATE_STORY = 'CREATE STORY FALLIDO';

export const SUCCEES_ACTIVE_STORIES = 'GET ACTIVE STORIES CON EXITO';
export const FAILED_ACTIVE_STORIES = 'GET ACTIVE STORIES FALLIDO';

export const SUCCEES_ACTIVE_GIFTS = 'GET ACTIVE GIFT CON EXITO';
export const FAILED_ACTIVE_GIFTS = 'GET ACTIVE GIFT FALLIDO';

export const SUCCEES_GET_ONE_ACTIVE_GIFTS = 'GET ONE GIFT CON EXITO';
export const FAILED_GET_ONE_ACTIVE_GIFTS = 'GET ONE GIFT FALLIDO';

export const SUCCEES_RECIVED_GIFTS = 'GET RECIVED GIFT CON EXITO';
export const FAILED_RECEVED_GIFTS = 'GET RECIVED GIFT FALLIDO';

export const SUCCEES_RECIVED_GIFTS_BY_USER = 'GET RECIVED GIFT BY USER CON EXITO';
export const FAILED_RECEVED_GIFTS_BY_USER = 'GET RECIVED GIFT BY USER FALLIDO';

export const SUCCEES_USER_STORIES = 'GET USER STORIES CON EXITO';
export const FAILED_USER_STORIES = 'GET USER STORIES FALLIDO';

export const SUCCEES_VIEW_STORY = 'VIEW STORY CON EXITO';
export const FAILED_VIEW_STORY = 'VIEW STORY FALLIDO';

export const SUCCEES_LIKE_STORY = 'LIKE STORY CON EXITO';
export const FAILED_LIKE_STORY = 'LIKE STORY FALLIDO';

export const SUCCEES_SEND_GIFT_STORY = 'LIKE STORY CON EXITO';
export const FAILED_SEND_GIFT_STORY = 'LIKE STORY FALLIDO';

export const SUCCEES_STORY_VIEWERS = 'GET STORY VIEWERS CON EXITO';
export const FAILED_STORY_VIEWERS = 'GET STORY VIEWERS FALLIDO';

export const SUCCEES_DELETE_STORY = 'DELETE STORY CON EXITO';
export const FAILED_DELETE_STORY = 'DELETE STORY FALLIDO';

export const SUCCESS_REPORT_STORY = 'REPORT STORY CON EXITO';
export const FAILED_REPORT_STORY = 'REPORT STORY FALLIDO';

export const SUCCEES_LIST_CHATS_ROOM = 'LIST CHATS ROOM CON EXITO';
export const FAILED_LIST_CHATS_ROOM = 'LIST CHATS ROOM FALLIDO';

export const LOADING_LOAD_MESSAGES = 'LOADING_LOAD_MESSAGES';
export const SUCCESS_LOAD_MESSAGES = 'SUCCESS_LOAD_MESSAGES';
export const FAILED_LOAD_MESSAGES = 'FAILED_LOAD_MESSAGES';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';

export const SUCCEES_SEND_MESSAGE = 'SEND MESSAGE CON EXITO';
export const FAILED_SEND_MESSAGE = 'SEND MESSAGE FALLIDO'
export const SUCCESS_GET_CONNECTIONS = 'GET CONNECTIONS CON EXITO';
export const FAILED_GET_CONNECTIONS = 'GET CONNECTIONS FALLIDO';

export const SUCCESS_GET_SUBSCRIPTIONS = 'GET SUBSCRIPTIONS CON EXITO';
export const FAILED_GET_SUBSCRIPTIONS = 'GET SUBSCRIPTIONS FALLIDO';

export const SUCCESS_CREATE_CHECKOUT = 'CREATE CHECKOUT CON EXITO';
export const FAILED_CREATE_CHECKOUT = 'CREATE CHECKOUT FALLIDO';

export const SUCCESS_SAVE_AVAILABILITY = 'SAVE AVAILABILITY CON EXITO'
export const FAILED_SAVE_AVAILABILITY = 'SAVE AVAILABILITY FALLIDO'
export const SUCCESS_GET_AVAILABILITY = 'GET AVAILABILITY CON EXITO'
export const FAILED_GET_AVAILABILITY = 'GET AVAILABILITY FALLIDO'

export const SUCCESS_GET_SOCIAL_ACCOUNTS = 'GET SOCIAL ACCOUNTS CON EXITO'
export const FAILED_GET_SOCIAL_ACCOUNTS = 'GET SOCIAL ACCOUNTS FALLIDO'
export const SUCCESS_DISCONNECT_SOCIAL = 'DISCONNECT SOCIAL CON EXITO'
export const FAILED_DISCONNECT_SOCIAL = 'DISCONNECT SOCIAL FALLIDO'

export const SUCCESS_GET_BANK_ACCOUNTS = 'GET BANK ACCOUNTS CON EXITO'
export const FAILED_GET_BANK_ACCOUNTS = 'GET BANK ACCOUNTS FALLIDO'
export const SUCCESS_ADD_BANK_ACCOUNT = 'ADD BANK ACCOUNT CON EXITO'
export const FAILED_ADD_BANK_ACCOUNT = 'ADD BANK ACCOUNT FALLIDO'
export const SUCCESS_DELETE_BANK_ACCOUNT = 'DELETE BANK ACCOUNT CON EXITO'
export const FAILED_DELETE_BANK_ACCOUNT = 'DELETE BANK ACCOUNT FALLIDO'

export const SUCCESS_UPDATE_PROFILE = 'UPDATE PROFILE CON EXITO'
export const FAILED_UPDATE_PROFILE = 'UPDATE PROFILE FALLIDO'

export const SUCCESS_GET_TOKEN_PACKAGES = 'SUCCESS_GET_TOKEN_PACKAGES';
export const FAILED_GET_TOKEN_PACKAGES = 'FAILED_GET_TOKEN_PACKAGES';

export const SUCCESS_GET_FOLLOWERS = 'SUCCESS_GET_FOLLOWERS';
export const FAILED_GET_FOLLOWERS = 'FAILED_GET_FOLLOWERS';
export const SUCCESS_GET_FOLLOWING = 'SUCCESS_GET_FOLLOWING';
export const FAILED_GET_FOLLOWING = 'FAILED_GET_FOLLOWING';
export const SUCCESS_GET_SUBSCRIBERS = 'SUCCESS_GET_SUBSCRIBERS';
export const FAILED_GET_SUBSCRIBERS = 'FAILED_GET_SUBSCRIBERS';
export const SUCCESS_GET_SUGGESTIONS = 'SUCCESS_GET_SUGGESTIONS';
export const FAILED_GET_SUGGESTIONS = 'FAILED_GET_SUGGESTIONS';

export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const APPEND_MEDIA = 'APPEND_MEDIA';
export const RESET_MEDIA = 'RESET_MEDIA';

export const SUCCESS_GET_TRANSACTIONS = 'SUCCESS_GET_TRANSACTIONS';
export const FAILED_GET_TRANSACTIONS  = 'FAILED_GET_TRANSACTIONS';
export const LOADING_GET_TRANSACTIONS = 'LOADING_GET_TRANSACTIONS';
export const APPEND_TRANSACTIONS      = 'APPEND_TRANSACTIONS';

export const SUCCESS_GET_BANNER  = 'SUCCESS_GET_BANNER';
export const FAILED_GET_BANNER   = 'FAILED_GET_BANNER';
export const DISMISS_BANNER      = 'DISMISS_BANNER';
